silverScore/projects/silverScore/care/urls.py
from django.urls import path
from . import views

app_name = 'care'

urlpatterns = [
    path('', views.index, name='index'),
]

silverScore/projects/silverScore/config/urls.py
from django.contrib import admin
from django.urls import path, include
from care import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('care/', include('care.urls')),
    path('member/', include('member.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),  # '/'에 해당되는 path
]

silverScore/projects/silverScore/member/urls.py
from django.urls import path

from . import views

app_name = 'member'

urlpatterns = [
    path('review/list/<int:longtermadmin_id>/', views.review_index, name='review_index'),
    path('review/create/<int:longtermadmin_id>/', views.review_create, name='review_create'),
    path('review/detail/<int:review_id>/', views.review_detail, name='review_detail'),
    path('review/modify/<int:review_id>/', views.review_modify, name='review_modify'),
    path('review/delete/<int:review_id>/', views.review_delete, name='review_delete'),
]

silverScore/projects/silverScore/member/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Member(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    passwd = models.CharField(max_length=15)
    phone = models.CharField(max_length=13)
    email = models.EmailField()
    registerDate = models.DateTimeField()

class SiDoGunGuCode(models.Model):
    id = models.AutoField(primary_key=True)
    siDoCd = models.CharField(max_length=2)
    siGunGuCd = models.CharField(max_length=3)
    siDoNm = models.CharField(max_length=20)
    siGunGuNm = models.CharField(max_length=20)


class AdminPttnCode(models.Model):
    adminPttnCd = models.CharField(max_length=3, primary_key=True)
    adminPttnNm = models.CharField(max_length=40)


class LongTermAdmin(models.Model):
    id = models.AutoField(primary_key=True)
    longTermAdminSym = models.CharField(max_length=11)
    adminPttnCd = models.CharField(max_length=3)
    siDoCd = models.CharField(max_length=2)
    siGunGuCd = models.CharField(max_length=3)
    adminNm = models.CharField(max_length=100)
    ratingCd = models.CharField(max_length=15, blank=True, null=True)
    ratingDate = models.DateField()
    ratingGrade = models.CharField(max_length=1)
    detailAddr = models.CharField(max_length=1000)
    telNo = models.CharField(max_length=18)
    jaehwalCd = models.CharField(max_length=1, blank=True, null=True)
    chimaeCd = models.CharField(max_length=1, blank=True, null=True)
    photo = models.ImageField(upload_to='images/', null=True)
    longTermPeribRgtDt = models.DateField()
    stpRptDt = models.DateField()
    adminCd = models.CharField(max_length=1)
    sidogungucode = models.ForeignKey(SiDoGunGuCode, on_delete=models.CASCADE)
    adminpttncode = models.ForeignKey(AdminPttnCode, on_delete=models.CASCADE)


class Review(models.Model):
    id = models.BigAutoField(primary_key=True)
    amKind = models.SmallIntegerField(default=0)
    faClean = models.SmallIntegerField(default=0)
    content = models.CharField(max_length=500, blank=True)
    createDate = models.DateTimeField()
    modifyDate = models.DateTimeField(null=True, blank=True)

#    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    longtermadmin = models.ForeignKey(LongTermAdmin, on_delete=models.CASCADE)

silverScore/projects/silverScore/member/forms.py
from django import forms
from member.models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review #사용할 모델
        fields = ['amKind', 'faClean', 'content'] #QuestionForm에서 사용할 Question 모델의 속성
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows':10}),
        # }
        labels = {
            'amKind': '분위기/친절도',
            'faClean': '시설/청결도',
            'content': '내용',
        }

silverScore/projects/silverScore/member/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .models import Review, LongTermAdmin
from .forms import ReviewForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.

def review_index(request, longtermadmin_id):
    longtermadmin = get_object_or_404(LongTermAdmin, pk=longtermadmin_id)
    page = request.GET.get('page', 1)   # 페이지
#    review_list = Review.objects.order_by('-createDate')
    review_list = Review.objects.filter(longtermadmin_id=longtermadmin_id).order_by('-createDate')
    paginator = Paginator(review_list, 10)    # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'longtermadmin': longtermadmin, 'review_list': page_obj}
    return render(request, 'member/review_list.html', context)

def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    context = {'review': review, 'longtermadmin': review.longtermadmin }
    return render(request, 'member/review_detail.html', context)
#    context = {'review': review}
#    return render(request, 'member/review_detail.html', context)

@login_required(login_url='common:login')
def review_create(request, longtermadmin_id):
    longtermadmin = get_object_or_404(LongTermAdmin, pk=longtermadmin_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():     # 폼이 유효하다면
            review = form.save(commit=False)  # 임시저장하여 review 객체를 리턴받는다.
            review.user = request.user
            review.createDate = timezone.localtime()   # 실제 저장을 위해 작성일시를 설정한다.
            review.longtermadmin = longtermadmin
            review.save()     # 데이터를 실제로 저장한다.
            return redirect('member:review_index', longtermadmin_id=longtermadmin.id)
    else:
        form = ReviewForm()
    context = {'longtermadmin':longtermadmin, 'form': form}
    return render(request, 'member/review_form.html', context)

@login_required(login_url='common:login')
def review_modify(request, review_id):
    review = get_object_or_404(Review, pk=review_id)

    if request.user != review.user :
        messages.error(request, '수정권한이 없습니다')
        return redirect('member:review_detail', review_id=review.id)
    if request.method == "POST" :
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            review = form.save(commit=False)
            review.modifyDate = timezone.now()   # 수정일시 저장
            review.save()
            return redirect('member:review_detail', review_id=review.id)
    else:
        form = ReviewForm(instance=review)
    context = {'review': review, 'longtermadmin': review.longtermadmin, 'form': form}
#    context = {'review': review, 'form': form}
    return render(request, 'member/review_modify.html', context)

@login_required(login_url='common:login')
def review_delete(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    if request.user != review.user:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('member:review_detail', review_id=review.id)
    review.delete()
    context = {'review': review, 'longtermadmin': review.longtermadmin, 'form': form}
    return render(request, 'member/review_list.html', context)
#    return redirect('member:review_index')

silverScore/projects/silverScore/templates/member/review_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <!--message 표시-->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <!--리뷰-->

    <h3 class="my-3 border-bottom py-2 text-danger">{{ longtermadmin.adminNm }} 후기 내용</h3>

    <!--
    <h3 class="border-bottom py-2 text-danger">후기 내용</h3>
    -->
    <div class="row">
        <h6 class="col">분위기/친절도</h6>
        <h6 class="col">시설/청결도</h6>
    </div>
    <div class="mb-3 row">
        <div class="col">
            <div class="rating">
                <div class="ratefill" id="ratefill1"></div>
                <!-- [D] 해당 별점이 선택될 때 그 점수 이하의 input엘리먼트에 checked 클래스 추가 -->
                <input type="checkbox" name="amKind" id="rating11" value="1" class="rate_radio" title="1점" disabled>
                <label for="rating11"></label>
                <input type="checkbox" name="amKind" id="rating12" value="2" class="rate_radio" title="2점" disabled>
                <label for="rating12"></label>
                <input type="checkbox" name="amKind" id="rating13" value="3" class="rate_radio" title="3점" disabled>
                <label for="rating13"></label>
                <input type="checkbox" name="amKind" id="rating14" value="4" class="rate_radio" title="4점" disabled>
                <label for="rating14"></label>
                <input type="checkbox" name="amKind" id="rating15" value="5" class="rate_radio" title="5점" disabled >
                <label for="rating15"></label>
            </div>
        </div>
        <div class="col">
            <div class="rating">
                <div class="ratefill" id="ratefill2"></div>
                <!-- [D] 해당 별점이 선택될 때 그 점수 이하의 input엘리먼트에 checked 클래스 추가 -->
                <input type="checkbox" name="faClean" id="rating21" value="1" class="rate_radio" title="1점" disabled>
                <label for="rating21"></label>
                <input type="checkbox" name="faClean" id="rating22" value="2" class="rate_radio" title="2점" disabled>
                <label for="rating22"></label>
                <input type="checkbox" name="faClean" id="rating23" value="3" class="rate_radio" title="3점" disabled>
                <label for="rating23"></label>
                <input type="checkbox" name="faClean" id="rating24" value="4" class="rate_radio" title="4점" disabled>
                <label for="rating24"></label>
                <input type="checkbox" name="faClean" id="rating25" value="5" class="rate_radio" title="5점" disabled>
                <label for="rating25"></label>
            </div>
        </div>
    </div>

    <form>
        <div class="mb-3">
        <label for="content" class="form-label">내용</label>
        <textarea class="form-control"
                  name="content" id="content" rows="10" maxlength="500" disabled>{{ review.content }}</textarea>
    </div>
    </form>

    <!--
    <div class="mb-3">
        <div class="form-label">내용</div>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ review.content }}</div>
                <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2"><strong>{{ review.user.username }}</strong></div>
                    <div><i class="fas fa-clock"></i> {{ review.createDate }}</div>
                </div>
            </div>
        </div>
        </div>
    </div>
    -->
    <div class="my-3">
        <a href="{% url 'member:review_index' longtermadmin.id %}" class="back_to_list btn btn-secondary">
            <i class="fas fa-list"></i> 목록으로 </a>

        {% if request.user == review.user %}
            <a href="{% url 'member:review_modify' review.id %}"
               class="btn btn-primary">후기 수정</a>
            <a href="javascript:void(0)" class="delete btn btn-primary"
               data-uri="{% url 'member:review_delete' review.id %}">후기 삭제</a>
        {% endif %}
    </div>
</div>
{% endblock %}k
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});

//별점 마킹 모듈 프로토타입으로 생성
function Rating(){};
Rating.prototype.rate = 0;
Rating.prototype.setRate = function(rateobj, newrate){
    //별점 마킹 - 클릭한 별 이하 모든 별 체크 처리
    this.rate = newrate;
	let checks = null;
	//요소가 파라메터로 넘어오면 별점 클릭, 없으면 저장 후 전체 초기화
	if(rateobj){
		rateobj.querySelector('.ratefill').style.width = parseInt(newrate * 60) + 'px'; // 현재 별점 갯수 채색
		checks = rateobj.querySelectorAll('.rate_radio'); // 넘어온 요소 하위의 라디오버튼만 선택
	}else{
		//전체 별점 채색 초기화
		const rateFills = document.querySelectorAll('.ratefill');
		rateFills.forEach(function(item){
			item.style.width = parseInt(newrate * 60) + 'px';
		});
		//전체 라디오 버튼 초기화
		checks = document.querySelectorAll('.rate_radio');
	}
	//별점 체크 라디오 버튼 처리
	if(checks){
		checks.forEach(function(item, idx){
			if(idx < newrate){
				item.checked = true;
			}else{
				item.checked = false;
			}
		});
	}
}

let rating = new Rating();//별점 인스턴스 생성

document.addEventListener('DOMContentLoaded', function(){
    //별점선택 이벤트 리스너
    const rateForms = document.querySelectorAll('.rating'); // 별점 선택 템플릿을 모두 선택
	rateForms.forEach(function(item){//클릭 이벤트 리스너 각각 등록
		item.addEventListener('click',function(e){
			let elem = e.target;
			if(elem.classList.contains('rate_radio')){
                rating.setRate(elem.parentElement, parseInt(elem.value)); // setRate() 에 ".rating" 요소를 첫 번째 파라메터로 넘김
			}
		})
	});
});

// Assuming review.amKind is the variable that stores the review score from the Django model
var review_amKind = {{ review.amKind }};
var review_faClean = {{ review.faClean }};
var amKind_width = review_amKind * 60;
var faClean_width = review_faClean * 60;

// Set the width of the .ratefill element
document.getElementById("ratefill1").style.width = amKind_width + "px";
document.getElementById("ratefill2").style.width = faClean_width + "px";
</script>
{% endblock %}
</body>
</html>

silverScore/projects/silverScore/templates/member/review_form.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h3 class="my-3 border-bottom pb-2 text-danger">후기 남기기</h3>
    <form method="post">

    {% csrf_token %}
    {% include "form_errors.html" %}

    <!--별점-->
    <div class="row">
        <h6 class="col">분위기/친절도</h6>
        <h6 class="col">시설/청결도</h6>
    </div>
    <div class="mb-3 row">
        <div class="col">
            <div class="rating">
                <div class="ratefill"></div>
                <!-- [D] 해당 별점이 선택될 때 그 점수 이하의 input엘리먼트에 checked 클래스 추가 -->
                <input type="checkbox" name="amKind" id="rating11" value="1" class="rate_radio" title="1점">
                <label for="rating11"></label>
                <input type="checkbox" name="amKind" id="rating12" value="2" class="rate_radio" title="2점">
                <label for="rating12"></label>
                <input type="checkbox" name="amKind" id="rating13" value="3" class="rate_radio" title="3점" >
                <label for="rating13"></label>
                <input type="checkbox" name="amKind" id="rating14" value="4" class="rate_radio" title="4점">
                <label for="rating14"></label>
                <input type="checkbox" name="amKind" id="rating15" value="5" class="rate_radio" title="5점">
                <label for="rating15"></label>
            </div>
        </div>
        <div class="col">
            <div class="rating">
                <div class="ratefill"></div>
                <!-- [D] 해당 별점이 선택될 때 그 점수 이하의 input엘리먼트에 checked 클래스 추가 -->
                <input type="checkbox" name="faClean" id="rating21" value="1" class="rate_radio" title="1점">
                <label for="rating21"></label>
                <input type="checkbox" name="faClean" id="rating22" value="2" class="rate_radio" title="2점">
                <label for="rating22"></label>
                <input type="checkbox" name="faClean" id="rating23" value="3" class="rate_radio" title="3점" >
                <label for="rating23"></label>
                <input type="checkbox" name="faClean" id="rating24" value="4" class="rate_radio" title="4점">
                <label for="rating24"></label>
                <input type="checkbox" name="faClean" id="rating25" value="5" class="rate_radio" title="5점">
                <label for="rating25"></label>
            </div>
        </div>
    </div>


    <div class="mb-3">
        <label for="content" class="form-label">내용</label>
        <textarea class="form-control" placeholder="이 리뷰는 요양기관을 찾는 분들께 큰 도움이 됩니다(최대500자)"
                  name="content" id="content" rows="10" maxlength="500" required></textarea>
            <!--{{ form.content.value|default_if_none:'' }}</textarea>-->
    </div>
    <button type="submit" class="btn btn-primary">후기 올리기</button>
  </form>
</div>

<script>
//별점 마킹 모듈 프로토타입으로 생성
function Rating(){};
Rating.prototype.rate = 0;
Rating.prototype.setRate = function(rateobj, newrate){
    //별점 마킹 - 클릭한 별 이하 모든 별 체크 처리
    this.rate = newrate;
	let checks = null;
	//요소가 파라메터로 넘어오면 별점 클릭, 없으면 저장 후 전체 초기화
	if(rateobj){
		rateobj.querySelector('.ratefill').style.width = parseInt(newrate * 60) + 'px'; // 현재 별점 갯수 채색
		checks = rateobj.querySelectorAll('.rate_radio'); // 넘어온 요소 하위의 라디오버튼만 선택
	}else{
		//전체 별점 채색 초기화
		const rateFills = document.querySelectorAll('.ratefill');
		rateFills.forEach(function(item){
			item.style.width = parseInt(newrate * 60) + 'px';
		});
		//전체 라디오 버튼 초기화
		checks = document.querySelectorAll('.rate_radio');
	}
	//별점 체크 라디오 버튼 처리
	if(checks){
		checks.forEach(function(item, idx){
			if(idx < newrate){
				item.checked = true;
			}else{
				item.checked = false;
			}
		});
	}
}

let rating = new Rating();//별점 인스턴스 생성

document.addEventListener('DOMContentLoaded', function(){
    //별점선택 이벤트 리스너
    const rateForms = document.querySelectorAll('.rating'); /* 별점 선택 템플릿을 모두 선택 */
	rateForms.forEach(function(item){//클릭 이벤트 리스너 각각 등록
		item.addEventListener('click',function(e){
			let elem = e.target;
			if(elem.classList.contains('rate_radio')){
				rating.setRate(elem.parentElement, parseInt(elem.value)); // setRate() 에 ".rating" 요소를 첫 번째 파라메터로 넘김
			}
		})
	});
});

</script>
{% endblock %}
</body>
</html>

silverScore/projects/silverScore/templates/member/review_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% load member_filter %}
{% block content %}
<div class="container my-3">
    <h3 class="border-bottom py-2 text-danger">{{ longtermadmin.adminNm }}</h3>
    <table class="table table-hover">
        <thead class="table-dark">
        <tr class="text-center">
            <th>no.</th>
            <th style="width:46%">내용</th>
            <th>분위기/친철도</th>
            <th>시설/청결도</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if review_list %}
        {% for review in review_list %}
        <tr class="text-left">
            <!--<td>{{ forloop.counter }}</td>-->
            <td>
                <!--번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1-->
                {{ review_list.paginator.count|sub:review_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a class="text-decoration-none"
                   href="{% url 'member:review_detail' review.id %}">{{ review.content|truncatechars:34 }}</a>
            </td>
            <td>{% for i in ""|ljust:review.amKind %}⭐{% endfor %}</td>
            <td>{% for i in ""|ljust:review.faClean %}⭐{% endfor %}</td>
            <td><span class="text-secondary small mx-2">{{ review.user.username }}</span></td>
            <td><span class="text-secondary small mx-2">{{ review.createDate }}</span></td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">후기가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!--페이징처리 시작-->
    <ul class="pagination justify-content-center">
        <!--이전페이지-->
        {% if review_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ review_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!--페이지리스트-->
        {% for page_number in review_list.paginator.page_range %}
        {% if page_number >= review_list.number|add:-5 and page_number <= review_list.number|add:5 %}
        {% if page_number == review_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!--다음페이지-->
        {% if review_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ review_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!--페이징처리 끝-->
    <a href="{% url 'member:review_create' longtermadmin.id %}" class="btn btn-primary">후기 남기기</a>
</div>
{% endblock %}

</body>
</html>

silverScore/projects/silverScore/templates/member/review_modify.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h3 class="my-3 border-bottom py-2 text-danger">{{ longtermadmin.adminNm }} 후기 수정</h3>
    <form method="post">

    {% csrf_token %}
    {% include "form_errors.html" %}

    <!--별점-->
    <div class="row">
        <h6 class="col">분위기/친절도</h6>
        <h6 class="col">시설/청결도</h6>
    </div>
    <div class="mb-3 row">
        <div class="col">
            <div class="rating">
                <div class="ratefill" id="ratefill1"></div>
                <!-- [D] 해당 별점이 선택될 때 그 점수 이하의 input엘리먼트에 checked 클래스 추가 -->
                <input type="checkbox" name="amKind" id="rating11" value="1" class="rate_radio" title="1점">
                <label for="rating11"></label>
                <input type="checkbox" name="amKind" id="rating12" value="2" class="rate_radio" title="2점">
                <label for="rating12"></label>
                <input type="checkbox" name="amKind" id="rating13" value="3" class="rate_radio" title="3점">
                <label for="rating13"></label>
                <input type="checkbox" name="amKind" id="rating14" value="4" class="rate_radio" title="4점">
                <label for="rating14"></label>
                <input type="checkbox" name="amKind" id="rating15" value="5" class="rate_radio" title="5점" >
                <label for="rating15"></label>
            </div>
        </div>
        <div class="col">
            <div class="rating">
                <div class="ratefill" id="ratefill2"></div>
                <!-- [D] 해당 별점이 선택될 때 그 점수 이하의 input엘리먼트에 checked 클래스 추가 -->
                <input type="checkbox" name="faClean" id="rating21" value="1" class="rate_radio" title="1점">
                <label for="rating21"></label>
                <input type="checkbox" name="faClean" id="rating22" value="2" class="rate_radio" title="2점">
                <label for="rating22"></label>
                <input type="checkbox" name="faClean" id="rating23" value="3" class="rate_radio" title="3점" >
                <label for="rating23"></label>
                <input type="checkbox" name="faClean" id="rating24" value="4" class="rate_radio" title="4점">
                <label for="rating24"></label>
                <input type="checkbox" name="faClean" id="rating25" value="5" class="rate_radio" title="5점">
                <label for="rating25"></label>
            </div>
        </div>
    </div>


    <div class="mb-3">
        <label for="content" class="form-label">내용</label>
        <textarea class="form-control"
                  name="content" id="content" rows="10" maxlength="500" required>{{ review.content }}</textarea>
    </div>

    <a href="{% url 'member:review_index' longtermadmin.id %}" class="back_to_list btn btn-secondary">
                <i class="fas fa-list"></i> 목록으로 </a>

    <button type="submit" class="btn btn-primary">수정 완료</button>
  </form>
</div>

<script>
//별점 마킹 모듈 프로토타입으로 생성
function Rating(){};
Rating.prototype.rate = 0;
Rating.prototype.setRate = function(rateobj, newrate){
    //별점 마킹 - 클릭한 별 이하 모든 별 체크 처리
    this.rate = newrate;
	let checks = null;
	//요소가 파라메터로 넘어오면 별점 클릭, 없으면 저장 후 전체 초기화
	if(rateobj){
		rateobj.querySelector('.ratefill').style.width = parseInt(newrate * 60) + 'px'; // 현재 별점 갯수 채색
		checks = rateobj.querySelectorAll('.rate_radio'); // 넘어온 요소 하위의 라디오버튼만 선택
	}else{
		//전체 별점 채색 초기화
		const rateFills = document.querySelectorAll('.ratefill');
		rateFills.forEach(function(item){
			item.style.width = parseInt(newrate * 60) + 'px';
		});
		//전체 라디오 버튼 초기화
		checks = document.querySelectorAll('.rate_radio');
	}
	//별점 체크 라디오 버튼 처리
	if(checks){
		checks.forEach(function(item, idx){
			if(idx < newrate){
				item.checked = true;
			}else{
				item.checked = false;
			}
		});
	}
}

let rating = new Rating();//별점 인스턴스 생성

document.addEventListener('DOMContentLoaded', function(){
    //별점선택 이벤트 리스너
    const rateForms = document.querySelectorAll('.rating'); // 별점 선택 템플릿을 모두 선택
	rateForms.forEach(function(item){//클릭 이벤트 리스너 각각 등록
		item.addEventListener('click',function(e){
			let elem = e.target;
			if(elem.classList.contains('rate_radio')){
                rating.setRate(elem.parentElement, parseInt(elem.value)); // setRate() 에 ".rating" 요소를 첫 번째 파라메터로 넘김
			}
		})
	});
});

// Assuming review.amKind is the variable that stores the review score from the Django model
var review_amKind = {{ review.amKind }};
var review_faClean = {{ review.faClean }};
var amKind_width = review_amKind * 60;
var faClean_width = review_faClean * 60;

// Set the width of the .ratefill element
document.getElementById("ratefill1").style.width = amKind_width + "px";
document.getElementById("ratefill2").style.width = faClean_width + "px";

for (var i = 0; i < 5; i++) {
  var amKindElement = document.getElementById("rating1" + (i + 1));
  var faCleanElement = document.getElementById("rating2" + (i + 1));
  if (i < review_amKind) {
    amKindElement.checked = true;
  } else {
    amKindElement.checked = false;
  }
  if (i < review_faClean) {
    faCleanElement.checked = true;
  } else {
    faCleanElement.checked = false;
  }
}
</script>
{% endblock %}
</body>
</html>