syoh/silverScore/projects/silverScore/care/urls.py
from django.urls import path

from . import views

app_name = 'care'

urlpatterns = [
    path('', views.CareListView.as_view(), name='care_index'),  # care_list의 기본
    # path(r'^search/$', views.CareSearchView.as_view(), name='care_search'),  # care_list에서 filter시
    path('<int:pk>/', views.CareDetailView.as_view(), name='care_detail'),
]

syoh/silverScore/projects/silverScore/common/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views  # login&logout
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.index, name='main'),
    path('signup/', views.SignUpView.as_view(template_name='common/signup.html'), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

syoh/silverScore/projects/silverScore/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from common import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('care/', include('care.urls')), # 요양원&리뷰
    path('common/', include(('common.urls', 'common'))),
    path('common/', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

syoh/silverScore/projects/silverScore/care/models.py
from django.db import models
from django.contrib.auth import get_user_model
from config import settings

# Create your models here.

# 요양원 - Care
# projects/silverScore/care/data/rankStatusData.csv
class Care(models.Model):
    id = models.AutoField(primary_key=True)
    longTermAdminCd = models.CharField(max_length=15)
    longTermAdminNm = models.CharField(max_length=100)
    adminPttnName = models.CharField(max_length=20)
    ratingCd = models.CharField(max_length=15)
    siDoName = models.CharField(max_length=20, blank=True, null=True)
    siGunGuName = models.CharField(max_length=20, blank=True, null=True)
    ratingDate = models.DateField(blank=True, null=True)
    ratingGrade = models.CharField(max_length=1, blank=True, null=True)
    opRating = models.IntegerField(blank=True, null=True)
    safeRating = models.IntegerField(blank=True, null=True)
    rightRating = models.IntegerField(blank=True, null=True)
    processRating = models.IntegerField(blank=True, null=True)
    resultRating = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering = ["ratingDate","ratingGrade"]

    # admin에서 보이기 위함
    def __str__(self):
        return f"{self.id} / 기관명 : {self.longTermAdminNm} / 기관기호 : {self.longTermAdminCd}"


# 주소 - Address
# projects/silverScore/care/data/addressNumbers.csv
class Address(models.Model):
    id = models.AutoField(primary_key=True)
    regionCd = models.IntegerField(blank=True, null=True)
    regionNm = models.CharField(max_length=200, blank=True, null=True)
    siDoNm = models.CharField(max_length=10, blank=True, null=True)
    siGunGuNm = models.CharField(max_length=10, blank=True, null=True)
    umdNm = models.CharField(max_length=10, blank=True, null=True)
    riNm = models.CharField(max_length=10, blank=True, null=True)
    siDoCd = models.IntegerField(blank=True, null=True)
    siGunGuCd = models.IntegerField(blank=True, null=True)
    DongCd = models.IntegerField(blank=True, null=True)
    riCd = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering = ["regionCd"]

    # admin에서 보이기 위함 AddressInfo.object(idx) 에서
    def __str__(self):
        return f"id : {self.id} / 법정동코드 : {self.regionCd} / 지역명 : {self.regionNm}"


# 리뷰 - Review
User = get_user_model()

class Review(models.Model):
    id = models.BigAutoField(primary_key=True)
    amKind = models.SmallIntegerField(default=0)
    faClean = models.SmallIntegerField(default=0)
    content = models.CharField(max_length=1500, blank=True)
    createDate = models.DateTimeField()
    modifyDate = models.DateTimeField(auto_now=True, null=True, blank=True)

#   member = models.ForeignKey(Member, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    longTermAdminCd = models.ForeignKey(Care, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-createDate']

    def __str__(self):
        return f"친절도 : {self.amKind} / 청결도 : {self.faClean} / 내용 : {self.content}"

syoh/silverScore/projects/silverScore/common/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

# Create your models here.

class ExtendUserForm(AbstractUser):
    # -> config/settings.py 에 AUTH_USER_MODEL = 'common.User' 로서 추가. why? : AbstractUser 로서 사용하므로
    phone_regex = RegexValidator(regex=r'^01([0|1|6|7|8|9])-?([0-9]{3,4})-?([0-9]{4})$') # 정규식 011-123-4567 혹은 010-1234-5678 기준
    phone = models.CharField(validators=[phone_regex], max_length=13, unique=True, verbose_name='phone') # 010-1234-5678 기준 갯수

    class Meta:
        abstract = False # True -> False 하니까 됨.

syoh/silverScore/projects/silverScore/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import ExtendUserForm

class SignupForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = ExtendUserForm
        fields = ['username', 'password1', 'password2', 'email', 'phone']


class ChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = ExtendUserForm
        fields = ['username', 'password', 'email', 'phone']

syoh/silverScore/projects/silverScore/care/views.py
# from django.http import Http404
# from django.shortcuts import render, get_object_or_404
# from django.core.exceptions import BadRequest
from django.views.generic import ListView, DetailView
from .models import Care, Address
# from .models import Review
from django.db.models import Q
from django.core.paginator import Paginator

# Create your views here.

# listview
class CareListView(ListView):
    model = Care
    template_name = 'care_list.html'
    paginate_by = 10  # 페이지당 10개씩 보여주기


    def get_context_data(self, **kwargs):
        context = super(CareListView, self).get_context_data(**kwargs)
        context['care_list'] = Care.objects.order_by('ratingGrade','-ratingCd')
        context['address_info'] = Address.objects.all()
        context['siDo_info'] = Address.objects.filter(siGunGuCd__gt=0, DongCd__gt=0).order_by('siDoCd','siGunGuCd','DongCd').values()

        # area filter
        siDoName = self.request.GET.get('siDoName')
        siGunGuName = self.request.GET.get('siGunGuName')
        search_input = self.request.GET.get('search_input')
        if siDoName:
            context['care_list'] = Care.objects.filter(
            Q(siDoName__icontains=siDoName)
            ).distinct()
        if siGunGuName:
            context['care_list'] = Care.objects.filter(
            Q(siDoName__icontains=siDoName) &
            Q(siGunGuName__icontains=siGunGuName)
            ).distinct()
        if search_input:
            context['care_list'] = Care.objects.filter(
                Q(longTermAdminNm__icontains=search_input) |
                Q(adminPttnName__icontains=search_input) |
                Q(ratingCd__icontains=search_input) |
                Q(siDoName__icontains=search_input) |
                Q(siGunGuName__icontains=search_input) |
                Q(ratingGrade__icontains=search_input)
            ).distinct()
        # pagination
        paginator = Paginator(context['care_list'], self.paginate_by)
        page = self.request.GET.get('page','1')
        context['care_list'] = paginator.get_page(page)

        return context

# deatilView
class CareDetailView(DetailView):
    model = Care # 사용할 메인 model
    template_name = 'care/care_detail.html'  # render할 path
    context_object_name = 'detail_info' # 해당의 view로 넘길 객체 이름

    # def get_queryset(self):
    #     return super().get_queryset()

    # def get_context_data(self, **kwargs):
    #     # context = super(CareListView, self).get_context_data(**kwargs)
    #     # context['address_info'] = Address.objects.all()
    #     return context

syoh/silverScore/projects/silverScore/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .forms import SignupForm
# Create your views here.


# index == 메인페이지
def index(request):
    # care_list = CareRank.objects.order_by('-ratingDate')
    # context = {'care_list': care_list}
    return render(request, 'common/main.html')

# 회원가입
class SignUpView(CreateView):
    form_class = SignupForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

syoh/silverScore/projects/silverScore/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="{% static 'icon/silverScore_favicon.png' %}" type="image/x-icon">
        <!-- google web font -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap">
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <!-- custom CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <!-- jquery-3.6.3.min.js -->
        <!-- <script type="text/javascript" src="{% static 'js/jquery-3.6.3.min.js' %}"></script> -->
        <!-- bxslider.com -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
        <!-- bootstrap.min.js -->
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <!-- custom.js -->
        <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
        <title>실버스코어</title>
    </head>
    <body>
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <footer class="footer">
        <h1><img src="{% static 'img/silverScore_logo.png' %}" alt="실버스코어 로고"></h1>
        <ul class="info">
            <li><strong>회사명 :</strong>(주)실버 스코어</li>
            <li><strong>서비스 문의 :</strong>admin@silverscore.com</li>
        </ul>
        <p class="rights">
            <a href="#">이용약관</a>
            <a href="#">개인정보처리방침</a>
            <a href="#">회사소개</a>
        </p>
        <p class="copyright">Copyright @ SilverScore Since 2022</p>
    </footer>
    </body>
</html>

syoh/silverScore/projects/silverScore/templates/care/care_list.html
{% extends 'base.html' %}
{% block title %}
<title>실버스코어 - 요양원 목록</title>
{% endblock %}

{% block content %}
<!-- S: care_list.html -->
<section class="care_list contatiner">
    <!-- 네비게이션바 -->
    <div class="searcharea">
    {% include './searchbar.html' %}
    </div>
    {% load carefilter %} <!-- care/templatetages/carefilter.py -->
    <div class="listarea">
        <h3>요양원 목록</h3>
        {% if care_list %}
        <ul class="center_list">
            {% for care in care_list %}
            <li>
                {% comment %} <a href="{% url 'care:care_detail' care.id %}"> {% endcomment %}
                <!-- window.open('url 'care:care_detail' care.id ', 'popup', 'width=800, height=600'); -->
                <a href="#" onclick="window.open('{% url 'care:care_detail' care.id %}', 'popup', 'width=1000, height=600, top=' + ((screen.height - 600) / 2) / 2 + ', left=' + (screen.width - 1000) / 2 + ', scrollbars=yes'); return false;">
                <p class="centerName"><strong>{{ care.longTermAdminNm }}</strong></p>
                <p class="area">
                    <strong>지역 : </strong>
                    <span>{{ care.siDoName }}</span>
                </p>
                <p class="grade">
                    <strong>등급 : </strong><span class="result">{{ care.ratingGrade }}</span>
                    <strong>평가 : </strong>
                    <span>{{ care.ratingCd }}</span>
                </p>
                <p class="img"></p>
            </a></li>
            {% endfor %}
        </ul>
        {% endif %}
        <!-- 페이징처리 시작 -->
        <div class="pagearea">
            <ul class="pagination justify-content-center">
                <!-- 처음페이지 -->
                <li class="page-item">
                    <a href="?page={{ 1 }}" class="page-link">처음</a>
                </li>
                <!-- 이전페이지 -->
                {% if care_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ care_list.previous_page_number }}">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
                {% endif %}
                <!-- 페이지리스트 -->
                {% for page_number in care_list.paginator.page_range %}
                {% if page_number >= care_list.number|add:-5 and page_number <= care_list.number|add:5 %}
                {% if page_number == care_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
                {% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>  <!-- tabindex="-1" 인 거 보면 그 전 부분인 듯. -->
                </li>
                {% endif %}
                <!-- 마지막페이지 -->
                <li class="page-item">
                    <a href="?page={{ care_list.paginator.num_pages }}" class="page-link">마지막</a>
                </li>
            </ul>
        </div>
        <!-- 페이징처리 끝 -->
    </div>
</section>
<!-- E: care_list.html -->
{% endblock %}

syoh/silverScore/projects/silverScore/templates/care/review.html
{% load static %}
<!-- S: review.html - popup_include -->
후기
<!-- E: review.html - popup_include -->

syoh/silverScore/projects/silverScore/templates/care/searchbar.html
{% load static %}
<!-- S: searchbar -->
<div class="searchBar">
    <div class="keyword">
        <h3>원하시는 키워드로 검색해보세요.</h3>
        <form action="{% url 'care:care_index' %}" method="get">
            <input type="text" name="search_input" placeholder="검색할 내용을 입력하세요" value="{{ request.GET.search_input }}">
            <button type="submit">검색</button>
        </form>
    </div>
    {% comment %} <div class="selectType">
        <h3>찾으시는 요양시설을 선택해 주세요.</h3>
        <ul>
            <li><a href="#">요양병원</a></li>
            <li><a href="#">요양원</a></li>
            <li><a href="#">주야간보호</a></li>
            <li><a href="#">방문시설</a></li>
        </ul>
    </div>
    <div class="filter">
        <h3>등급 등 원하는 조건이 있나요?</h3>
        <p class="btnarea">
            <button class="filterbtn"><img src="{% static "icons/png/002-filter.png" %}" alt="조건 필터"></button>
            <span>버튼을 눌러주세요!</span>
        </p>
    </div> {% endcomment %}
    <div class="area">
        <h3>원하시는 지역을 선택해주세요.</h3>
        {% load carefilter %}
        <div class="region container my-3">
            <!-- basic list -->
            {% if siDo_info %}
            <ul class="regionList">
                {% regroup siDo_info by siDoNm as address_list %}
                {% for siDoNm in address_list %}
                <li class="siDo"><a href="{% url 'care:care_index' %}?siDoName={{ siDoNm.grouper }}">{{ siDoNm.grouper }}</a></li><!--|default_if_none:''-->
                {% regroup siDoNm.list by siGunGuNm as siGungu_list %}
                <ul class="siGunGuList">
                    {% for gunGu in siGungu_list %}
                    <li><a href="{% url 'care:care_index' %}?siDoName={{ siDoNm.grouper }}&siGunGuName={{ gunGu.grouper }}">{{ gunGu.grouper }}</a></li>
                    {% endfor %}
                </ul>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
<!-- E: searchbar -->

syoh/silverScore/projects/silverScore/templates/common/login.html
{% extends "base.html" %}
{% block title %}
<title>실버스코어 - 로그인</title>
{% endblock %}

{% block content %}
<!-- S: login.html -->
<div class="container my-3 userform">
    <h1>로그인</h1>
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username" class="userform_label">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password" class="userform_label">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
<!-- E: login.html -->
{% endblock %}

syoh/silverScore/projects/silverScore/templates/common/main.html
{% extends "base.html" %}
{% block title %}
메인페이지 - 실버스코어
{% endblock %}

{% block content %}
<!-- S: main.html -->
{% load static %}
<section class="main">
    <div class="container slider">
        <div class="box">
            <p class="text">
                <span class="line">실버 스코어에서</span>
                <span class="line">노인을 위한 요양기관에 대한 정보를 제공합니다.</span>
            </p>
            <p class="image"><img src="{% static 'img/003.jpg' %}" alt=""></p>
        </div>
        <div class="box">
            <p class="text">
                <span class="line">요양기관을 검색해 보세요.</span>
                <span class="line">원하시는 곳을 찾아드립니다.</span>
            </p>
            <p class="image"><img src="{% static 'img/005.jpg' %}" alt=""></p>
        </div>
    </div>
</section>
<!-- main page slider -->
<script type="text/javascript">
    $(document).ready(function(){
      $('.slider').bxSlider({
        mode: 'fade',
        auto: true,
        autoControls: true,
        stopAutoOnClick: true,
        pager: true,
      });
    });
  </script>
<!-- E: main.html -->
{% endblock %}

syoh/silverScore/projects/silverScore/templates/common/signup.html
{% extends "base.html" %}
{% block title %}
<title>실버스코어 - 회원가입</title>
{% endblock %}

{% block content %}
<!-- S: signup.html -->
<div class="container userform">
    <h1>회원가입</h1>
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username" class="userform_label">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}" title="150자 이하 문자, 숫자 그리고 @/./+/-/_만 가능합니다." required>
        </div>
        <div class="mb-3">
            <label for="password1" class="userform_label">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}" minlength="8" title="비밀번호는 최소 8자여야 하며, 숫자 및 영문 조합이어야 합니다. 또한 다른 개인정보와 유사해서는 안됩니다." required>
        </div>
        <div class="mb-3">
            <label for="password2" class="userform_label">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}" minlength="8" placeholder="확인을 위해 이전과 동일한 비밀번호를 입력하세요." required>
        </div>
        <div class="mb-3">
            <label for="phone" class="userform_label">휴대폰번호</label>
            <input type="phone" class="form-control" name="phone" id="phone" value="{{ form.phone.value|default_if_none:'' }}" placeholder="010-1234-5678 형식으로 입력해주세요." required>
        </div>
        <div class="mb-3">
            <label for="email" class="userform_label">이메일</label>
            <input type="email" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}" placeholder="example@test.com">
        </div>
        <button type="submit" class="btn btn-primary">회원가입</button>
    </form>
</div>
<!-- E: signup.html -->
{% endblock %}

syoh/silverScore/projects/silverScore/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

syoh/silverScore/projects/silverScore/templates/navbar.html
{% load static %}
<!-- S: navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand logo" href="{% url 'index' %}"><img src="{% static 'img/silverScore_logo.png' %}" alt="실버스코어 로고"></a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 navul">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'care:care_index' %}">요양기관 검색</a>
                </li>
                <li>
                    <a class="nav-link" href="#">지도 검색</a>
                </li>
                <li>
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">로그아웃</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                {% if user.is_authenticated %}
                {% else %}
                <li>
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- E: navbar -->