silverScore/projects/silverScore/care/urls.py
from django.urls import path
from . import views

app_name = 'care'

urlpatterns = [
    path('', views.index, name='index'),
]

silverScore/projects/silverScore/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

silverScore/projects/silverScore/config/urls.py
from django.contrib import admin
from django.urls import path, include
from care import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('care/', include('care.urls')),
    path('member/', include('member.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),  # '/'에 해당되는 path
]

silverScore/projects/silverScore/member/urls.py
from django.urls import path

from . import views

app_name = 'member'

urlpatterns = [
    path('review/list/<int:longtermadmin_id>/', views.review_index, name='review_index'),
    path('review/create/<int:longtermadmin_id>/', views.review_create, name='review_create'),
    path('review/detail/<int:review_id>/', views.review_detail, name='review_detail'),
    path('review/modify/<int:review_id>/', views.review_modify, name='review_modify'),
    path('review/delete/<int:review_id>/', views.review_delete, name='review_delete'),
]

silverScore/projects/silverScore/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- 별점 CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'rating.css' %}">
    <!-- 개발자 CSS -->
    <!--<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <title>SilverScore</title>
</head>
<body>
<!--내비게이션바-->
{% include "navbar.html" %}
<!--기본 템플릿 안에 삽입될 내용 Start-->
{% block content %}
{% endblock %}
<!--기본 템플릿 안에 삽입될 내용 End-->
<!-- 먼저 jQuery 자바스크립트 적용-->
<script src="{% static 'jquery-3.6.3.min.js' %}"></script>
<!--bootstrap 자바스크립트 적용-->
<script src="{% static 'bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}
<!--자바스크립트 End-->
</body>
</html>

silverScore/projects/silverScore/templates/form_errors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--필드 오류와 넌필드 오류를 출력한다.-->
{% if form.errors %}
<div class="alert alert-danger">
  {% for field in form %}
  <!--필드 오류-->
  {% if field.errors %}
  <div>
    <strong>{{ field.label }}</strong>
    {{ field.errors }}
  </div>
  {% endif %}
  {% endfor %}
  <!--넌필드 오류-->
  {% for error in form.non_field_errors %}
  <div>
    <strong>{{ error }}</strong>
  </div>
  {% endfor %}
</div>
{% endif %}
</body>
</html>

silverScore/projects/silverScore/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--내비게이션바-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
     <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'member:review_index' 1 %}">SilverScore</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item" >
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">
                        <i class="fas fa-sign-out-alt"></i> {{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">
                        <i class="fas fa-sign-in-alt"></i> 로그인 </a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">
                        <i class="fas fa-user-plus"></i> 회원가입 </a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>
</body>
</html>